# Generated by Django 4.2.16 on 2024-11-14 23:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pizzaria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data de criação do carrinho",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "finalizado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o carrinho foi finalizado",
                        verbose_name="Finalizado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário dono do carrinho",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrinhos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrinho",
                "verbose_name_plural": "Carrinhos",
            },
        ),
        migrations.AlterField(
            model_name="categoria",
            name="ativa",
            field=models.BooleanField(
                default=True,
                help_text="Indica se esta categoria está ativa para uso",
                verbose_name="Ativa",
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada da categoria",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                help_text="Nome da categoria de pizza",
                max_length=50,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="categoria",
            field=models.ForeignKey(
                help_text="Categoria à qual esta pizza pertence",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pizzas",
                to="pizzaria.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Data da última atualização",
                verbose_name="Data de Atualização",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Data de criação do registro",
                verbose_name="Data de Cadastro",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="descricao",
            field=models.TextField(
                help_text="Descrição detalhada da pizza com ingredientes",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="disponivel",
            field=models.BooleanField(
                default=True,
                help_text="Indica se esta pizza está disponível para venda",
                verbose_name="Disponível",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto da pizza",
                null=True,
                upload_to="pizzas/",
                verbose_name="Foto",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="nome",
            field=models.CharField(
                help_text="Nome da pizza", max_length=100, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="preco",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Preço da pizza em reais",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Preço",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="tamanho",
            field=models.CharField(
                choices=[
                    ("P", "Pequena"),
                    ("M", "Média"),
                    ("G", "Grande"),
                    ("F", "Família"),
                ],
                help_text="Tamanho da pizza",
                max_length=1,
                verbose_name="Tamanho",
            ),
        ),
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantidade de pizzas",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço unitário da pizza no momento da adição ao carrinho",
                        max_digits=6,
                        verbose_name="Preço Unitário",
                    ),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        help_text="Carrinho ao qual este item pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pizzaria.carrinho",
                        verbose_name="Carrinho",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        help_text="Pizza selecionada",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_carrinho",
                        to="pizzaria.pizza",
                        verbose_name="Pizza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Carrinho",
                "verbose_name_plural": "Itens do Carrinho",
            },
        ),
    ]
