# Generated by Django 5.1.4 on 2024-12-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0002_carrinho_alter_categoria_ativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='pizza',
            field=models.ForeignKey(help_text='Pizza selecionada', on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='pizzaria.pizza', verbose_name='Pizza'),
        ),
    ]
